In [1]:
import numpy as np

In [2]:
Q = np.empty((9,9))
Q[:] = np.nan

In [3]:
Q

array([[nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan]])

In [4]:
Q[0,[0,1,3]] = 0
Q[1,[0,1,2,4]] = 0
Q[2,[1,2,5]] = 0
Q[3,[0,3,4]] = 0
Q[4,[1,3,4,5,7]] = 0
Q[5,[2,4,5,8]] = 0
Q[6,[3,6,7]] = 0
Q[7,[4,6,7,8]] = 0
Q[8,[5,7,8]] = 0

In [5]:
Q

array([[ 0.,  0., nan,  0., nan, nan, nan, nan, nan],
       [ 0.,  0.,  0., nan,  0., nan, nan, nan, nan],
       [nan,  0.,  0., nan, nan,  0., nan, nan, nan],
       [ 0., nan, nan,  0.,  0., nan, nan, nan, nan],
       [nan,  0., nan,  0.,  0.,  0., nan,  0., nan],
       [nan, nan,  0., nan,  0.,  0., nan, nan,  0.],
       [nan, nan, nan,  0., nan, nan,  0.,  0., nan],
       [nan, nan, nan, nan,  0., nan,  0.,  0.,  0.],
       [nan, nan, nan, nan, nan,  0., nan,  0.,  0.]])

In [6]:
R = Q
idx = np.isnan(R[:,4])
R[~idx,4] = -1
idx = np.isnan(R[:,8])
R[~idx,8] = 1

In [7]:
R

array([[ 0.,  0., nan,  0., nan, nan, nan, nan, nan],
       [ 0.,  0.,  0., nan, -1., nan, nan, nan, nan],
       [nan,  0.,  0., nan, nan,  0., nan, nan, nan],
       [ 0., nan, nan,  0., -1., nan, nan, nan, nan],
       [nan,  0., nan,  0., -1.,  0., nan,  0., nan],
       [nan, nan,  0., nan, -1.,  0., nan, nan,  1.],
       [nan, nan, nan,  0., nan, nan,  0.,  0., nan],
       [nan, nan, nan, nan, -1., nan,  0.,  0.,  1.],
       [nan, nan, nan, nan, nan,  0., nan,  0.,  1.]])

In [8]:
MAXITER = 1000
NUMSTATES = 9
eta = 0.99
for k in range(MAXITER):
    alpha = 1/(k+1)
    Q2 = Q.copy()
    pk = 1 - (10/(20+k))
    selectMax = False
    if np.random.rand()<pk:
        selectMax = True
    for i in range(NUMSTATES):
        idx = np.isnan(R[i,:])
        allowedStates = np.arange(NUMSTATES)[~idx]
        j = Q[i,allowedStates].argmax()
        if selectMax:
            j = allowedStates[j]
        else:
            allowedStates = np.delete(allowedStates,j)
            j = np.random.permutation(allowedStates)[0]
        Q2[i,j] = (1-alpha**k)*Q[i,j]+(alpha**k)*(R[i,j]+eta*np.nanmax(Q[j,:]))
    Q = Q2.copy()

In [9]:
Q

array([[ 1.80682035e-33,  5.07768405e-07,             nan,
         1.62006436e-22,             nan,             nan,
                    nan,             nan,             nan],
       [ 6.33339257e-22,  1.32704276e-29,  3.72937122e-03,
                    nan, -9.99999999e-01,             nan,
                    nan,             nan,             nan],
       [            nan,  4.65164268e-18,  3.41389987e-03,
                    nan,             nan,  2.21717671e-01,
                    nan,             nan,             nan],
       [ 4.24433647e-12,             nan,             nan,
         1.62006436e-22, -1.00000000e+00,             nan,
                    nan,             nan,             nan],
       [            nan,  5.39676469e-06,             nan,
         5.29395854e-27, -9.99999999e-01,  7.60160749e-11,
                    nan,  8.30759267e-86,             nan],
       [            nan,             nan,  3.38610938e-03,
                    nan, -9.99999999e-01,  9.850500

In [12]:
i = 4
NUMTRAS = 10
for k in range(NUMTRAS):
    print(i)
    idx = np.isnan(Q[i,:])
    allowedStates = np.arange(9)[~idx]
    j = Q[i,allowedStates].argmax()
    j = allowedStates[j]
    i = j

4
1
2
5
8
8
8
8
8
8
